function EFFECT:Init(data)
	local pos = data:GetOrigin()
	local emitter = ParticleEmitter(pos)
	
		local flare = emitter:Add("effects/serioussam2/flares/flare_star01", pos)
			flare:SetVelocity(Vector(0,0,0))
			flare:SetAirResistance(0)
			flare:SetGravity(Vector(0, 0, 0))
			flare:SetDieTime(.5)
			flare:SetStartAlpha(255)
			flare:SetEndAlpha(0)
			flare:SetStartSize(50)
			flare:SetEndSize(120)
			flare:SetRoll(math.Rand(-90, 90))
			flare:SetRollDelta(0)
			flare:SetColor(255, 240, 0)

		local flare1 = emitter:Add("effects/serioussam2/flares/flare_star01", pos)
			flare1:SetVelocity(Vector(0,0,0))
			flare1:SetAirResistance(0)
			flare1:SetGravity(Vector(0, 0, 0))
			flare1:SetDieTime(.6)
			flare1:SetStartAlpha(255)
			flare1:SetEndAlpha(0)
			flare1:SetStartSize(20)
			flare1:SetEndSize(100)
			flare1:SetRoll(math.Rand(-90, 90))
			flare1:SetRollDelta(0)
			flare1:SetColor(255, 255, 50)
			
		local flare2 = emitter:Add("effects/serioussam2/flares/flare_star01", pos)
			flare2:SetVelocity(Vector(0,0,0))
			flare2:SetAirResistance(0)
			flare2:SetGravity(Vector(0, 0, 0))
			flare2:SetDieTime(.65)
			flare2:SetStartAlpha(255)
			flare2:SetEndAlpha(0)
			flare2:SetStartSize(80)
			flare2:SetEndSize(40)
			flare2:SetRoll(math.Rand(-90, 90))
			flare2:SetRollDelta(0)
			flare2:SetColor(255, 255, 150)
		
		for i = 0,8 do
			local fire = emitter:Add("particle/particle_smokegrenade", pos)
			fire:SetVelocity(VectorRand() * math.Rand(10,20))
			fire:SetAirResistance(100)
			fire:SetGravity(Vector(0, 0, 120))
			fire:SetDieTime(math.Rand(.6, .8))
			fire:SetStartAlpha(255)
			fire:SetEndAlpha(0)
			fire:SetStartSize(math.Rand(10, 15))
			fire:SetEndSize(math.Rand(15, 25))
			fire:SetRoll(math.Rand(-90, 90))
			fire:SetRollDelta(math.Rand(-1, 1))
			fire:SetColor(255, 100, 0)
		end
		
		for i = 0,14 do
			local sparks = emitter:Add("effects/serioussam2/flares/flare_star01", pos)
			sparks:SetVelocity(VectorRand() * 120 + Vector(0,0,50))
			sparks:SetAirResistance(0)
			sparks:SetGravity(Vector(0, 0, -300))
			sparks:SetDieTime(math.Rand(.5, .9))
			sparks:SetStartAlpha(255)
			sparks:SetEndAlpha(200)
			sparks:SetStartSize(math.Rand(1, 2))
			sparks:SetEndSize(math.Rand(8, 10))
			sparks:SetRoll(math.Rand(-90, 90))
			sparks:SetRollDelta(math.Rand(-.4, .4))
			sparks:SetColor(255, 200, 100)
		end
		
		local wave = emitter:Add("effects/serioussam2/flares/whitebubble02", pos)
			wave:SetVelocity(Vector(0,0,0))
			wave:SetAirResistance(0)
			wave:SetGravity(Vector(0, 0, 0))
			wave:SetDieTime(.3)
			wave:SetStartAlpha(255)
			wave:SetEndAlpha(0)
			wave:SetStartSize(2)
			wave:SetEndSize(60)
			wave:SetRoll(math.Rand(-90, 90))
			wave:SetRollDelta(0)
			wave:SetColor(255, 180, 10)

	emitter:Finish()
end

function EFFECT:Think()
	return false
end

function EFFECT:Render()
end