MT_IGSItem.End = function() end
MT_IGSItem.SetRealPrice = function( self ) return self end

local function AddSkin( sName, sClass, nPrice, sIcon, sImage )
	local item = IGS( sName, sClass )
	:SetPrice( nPrice )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( 'Перма Скины' )
	:SetNetworked( true )
	:SetIcon( sIcon or 'https://ltdfoto.ru/images/2024/09/14/chrome_OFXNsepPR9.png' )
	:SetImage( sImage or 'https://ltdfoto.ru/images/2024/09/14/JVDEIhNVKt.png' )
	:SetDescription( 'Модель навсегда\nТретье лицо - F7' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за покупку! Взять скин через С Меню -> Пермаскины (Третье лицо - F7)' )

		Ambi.UI.Chat.SendAll( '~W~ 🥳 '..ePly:Name()..' купил скин '..sName..' [F6]' )
		Ambi.UI.Sound.PlayAll( 'ambi/ui/click_tower_unite.wav' )
	end )

	return item
end

local function AddWeapon( sName, sClass, nPrice, sModel )
	local item = IGS( sName, sClass )
	:SetPrice( nPrice )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( 'Перма Оружия' )
	:SetNetworked( true )
	:SetIcon( sModel or '', true )
	:SetDescription( 'Оружие навсегда\nЕсть задержка в несколько минут\nНельзя дропать (в /kit можно)' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за покупку! Взять оружие через С Меню -> Перма Оружия' )
		ePly:PlaySound( 'ambi/ui/click_tower_unite.wav' )
	end )

	return item
end

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Секретные Технологии'

IGS( 'Убивашка', 'perma_wep_weldor' )
	:SetPrice( 4000 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetNetworked( true )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/14/UBIVASKA1.png' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/14/JVDEIhNVKt.png' )
	:SetDescription( 'Оружие навсегда\nЗадержка 1 минут(ы)\nНельзя дропать (в /kit можно)\n\n• 9999 Урона\n• Мгновенная перезарядка\n• Интересный звук\n• Особый скин\n• Дальность 1200 метров' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за покупку! Взять оружие через С Меню -> Перма Оружия' )

		Ambi.Homeway.NotifyAll( ePly:Name()..' ахуел и купил Убивашку', 15, NOTIFY_ACCEPT )
	end )
:End()

IGS( 'Гаусска', 'perma_wep_gauss' )
	:SetPrice( 1500 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetNetworked( true )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/14/GAUSSKA.png' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/14/gmod_8NLTvS00Dq.jpg' )
	:SetDescription( 'Оружие навсегда\nЗадержка 3 минут(ы)\nНельзя дропать (в /kit можно)' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за покупку! Взять оружие через С Меню -> Перма Оружия' )

		Ambi.Homeway.NotifyAll( ePly:Name()..' афигел и купил Гаусску', 15, NOTIFY_ACCEPT )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Сундуки'

IGS( '+Обычный', 'chest' )
	:SetPrice( 50 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_d', 1 )
	end )
:End()

IGS( '+Еда', 'chest_food' )
	:SetPrice( 75 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Особая еда, даёт сильные баффы/дебаффы' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_food_d', 1 )
	end )
:End()

IGS( '+Оружейный', 'chest_weapons' )
	:SetPrice( 99 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Перманентные оружия' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest_weapon.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_weapons_d', 1 )
	end )
:End()

IGS( '+Денежный', 'chest_money' )
	:SetPrice( 145 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Игровая валюта: 10k, 50k, 175k, 250k, 500k\nДонат валюта: 25, 50, 150' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest_money.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_money_d', 1 )
	end )
:End()

IGS( '+Донат Валюта', 'chest_rubles' )
	:SetPrice( 180 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Только донат валюта: 50, 100, 150, 250, 400, 800' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest_money.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_money_rubles_d', 1 )
	end )
:End()

IGS( '+Бусты', 'chest_boosts' )
	:SetPrice( 240 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Даёт очень сильные бусты на 2 минуты' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_boost_d', 1 )
	end )
:End()

IGS( '+Скины', 'chest_skin' )
	:SetPrice( 400 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Даёт перма скины' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/chest.png' )
	:SetOnActivate( function( ePly )
		ePly:Notify( 'Вы купили сундук! Он в инвентаре', 15 )
		ePly:AddInvItemOrDrop( 'chest_skins_d', 1 )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------

AddSkin( 'Лучше Звоните Солу', 'perma_skin_soul_goodman', 99, 'https://ltdfoto.ru/images/2024/08/21/chrome_WtSM8PTNi0.png', 'https://ltdfoto.ru/images/2024/08/21/gmod_v4vPCQocED.png' )
AddSkin( 'EFT Дед', 'perma_skin_eft_partisan', 99, 'https://ltdfoto.ru/images/2024/09/13/gmod_MSx6w8t6eE.jpg', 'https://ltdfoto.ru/images/2024/09/13/gmod_R6EQ5PBK2j.jpg' )
AddSkin( 'Маньяк', 'perma_skin_murder', 150, 'https://ltdfoto.ru/images/2024/09/15/gmod_EKohiF1YkL.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_YAsmPHapNM.jpg' )
AddSkin( 'Гомункул', 'perma_skin_gang_beast', 200, 'https://ltdfoto.ru/images/2024/09/15/chrome_4JpryXv7I4.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_IbVd5l0uMZ.jpg' )
AddSkin( 'Сухарик', 'perma_skin_coal', 300, 'https://ltdfoto.ru/images/2024/09/14/gmod_rnpM6Kghjx.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_gClbl8KXpR.png' )
AddSkin( 'Дрыщ', 'perma_skin_skelet', 350, 'https://ltdfoto.ru/images/2024/09/15/chrome_R2DUeLE68f.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_GK9S5jUGES.jpg' )
AddSkin( 'Бибизян', 'perma_skin_bibizyana', 400, 'https://ltdfoto.ru/images/2024/09/15/194978.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_XyNhcLZAbt.jpg' )
AddSkin( 'Тюбик', 'perma_skin_colgate', 500, 'https://ltdfoto.ru/images/2024/09/15/chrome_3FI8w0aO98.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_mboWfmRZ56.jpg' )
AddSkin( 'Grox', 'perma_skin_crox', 550, 'https://ltdfoto.ru/images/2024/09/15/chrome_uZz8lyVZHo.png', 'https://ltdfoto.ru/images/2024/09/15/gmod_wxiawj2FyO.jpg' )
AddSkin( 'Мадара Учиха', 'perma_skin_madara', 600, 'https://ltdfoto.ru/images/2024/09/14/chrome_wsdebtwZqc.md.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_JXJhnxjycM.png' )
AddSkin( 'Ягами Лайт', 'perma_skin_yagami', 900, 'https://ltdfoto.ru/images/2024/09/14/chrome_6uJzcbp7lC.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_Yozv3029gG.png' )
AddSkin( 'Пошлая', 'perma_skin_whore', 1200, 'https://ltdfoto.ru/images/2024/09/14/chrome_N9Zqf7myaM.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_Pi4XWnTPgj.png' )
AddSkin( 'Апония', 'perma_skin_aponia', 2000, 'https://ltdfoto.ru/images/2024/09/14/chrome_oBYXQXw2Rw.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_e5fWcBy0xJ.png' )
AddSkin( '2B', 'perma_skin_2b', 2200, 'https://ltdfoto.ru/images/2024/08/21/chrome_YRMjx8X7kC.png', 'https://ltdfoto.ru/images/2024/08/21/zYazErABqR.jpg' )
AddSkin( 'Дьяволица', 'perma_skin_diablo', 2500, 'https://ltdfoto.ru/images/2024/09/14/chrome_T7rwmqryrj.png', 'https://ltdfoto.ru/images/2024/09/14/gmod_FLRb10zeXU.png' )

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Perma Оружия'

AddWeapon( 'Desert Eagle', 'perma_wep_deagle', 75, 'models/weapons/w_pist_deagle.mdl' )
AddWeapon( 'AK-47', 'perma_wep_ak47', 99, 'models/weapons/arccw/w_type2.mdl' )
AddWeapon( 'AWP', 'perma_wep_awp', 150, 'models/weapons/arccw/w_hs338.mdl' )
AddWeapon( 'Пулемёт', 'perma_wep_m14', 180, 'models/weapons/arccw/w_m2000g.mdl' )
AddWeapon( 'RPG-7', 'perma_wep_rpg', 300, 'models/weapons/arccw/w_rpg7.mdl' )

AddWeapon( '[SS2] Двустволка', 'perma_wep_ss2_doubleshtg', 350, 'models/serioussam2/weapons/w_autoshotgun.mdl' )
AddWeapon( '[SS2] Револьверы', 'perma_wep_ss2_colt', 500, 'models/serioussam2/weapons/w_colt.mdl' )
AddWeapon( '[SS2] Узи', 'perma_wep_ss2_uzi', 700, 'models/serioussam2/weapons/w_uzi.mdl' )
AddWeapon( '[SS2] Ракетница', 'perma_wep_ss2_rocket', 750, 'models/serioussam2/weapons/w_rocketlauncher.mdl' )

AddWeapon( '[HI] Verdict', 'perma_wep_hm_verdict', 800, 'models/weapons/arccw/bh_melee/w_verdict.mdl' )
AddWeapon( '[HI] Katana', 'perma_wep_hm_katana', 1000, 'models/weapons/arccw/bh_melee/w_katana.mdl' )
AddWeapon( '[HI] Перо', 'perma_wep_hm_fan', 1500, 'models/weapons/arccw/bh_melee/w_frying_pan.mdl' )
AddWeapon( '[HI] Уничтожитель', 'perma_wep_hm_sickle', 2500, 'models/weapons/arccw/bh_melee/w_shovel.mdl' )

AddWeapon( '[CF] Дикий Дигл', 'perma_wep_cf_deagle', 400, 'models/cf/w_deagle_beast.mdl' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/16/gmod_Crca24bQbs.jpg' )
AddWeapon( '[CF] M4A1', 'perma_wep_cf_m4a1', 800, 'models/cf/w_m4a1_beast.mdl' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/16/gmod_nLzNkT3JRH.jpg' )
AddWeapon( '[CF] Огненная AK-47', 'perma_wep_cf_ak47', 1600, 'models/cf/w_ak47_beast.mdl' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/16/gmod_S6iBrqd0LJ.jpg' )

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Обновления'

IGS( 'Второй квест', 'update_two_quest' )
	:SetPrice( 4000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Понравился первый квест? У нас в планах есть разработка второго квеста!\nТы можешь ускорить этот процесс!\n - При покупке, одну неделю квест будет доступен только тебе, после недели доступ откроется всем' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Улучшения для фракции', 'update_fractions' )
	:SetPrice( 6000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Надоело ждать обновления с фракциями? Ты можешь купить данную услугу и мы реализуем фракции за пару дней!\n- При покупке, одну неделю фракция будет доступна только тебе, после недели доступ откроется всем' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Хитманы', 'update_hitman' )
	:SetPrice( 7000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Крупное обновление: Фракция Хитманов \nГде есть отель Континталь\nИ ваша задача выполнять заказы\nОт системы, либо от людей\nСистема прокачки и новые работы\nСвоя валюта' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Привилегия'

IGS( 'VIP [30 Дней]', 'priv1' )
	:SetPrice( 99 )
	:SetTerm( 30 )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/vip.png' )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '- 3-е лицо\n- Перма оружие\nКрасивый таб\nБольше места в инвентаре\nВдвое быстрее экран после смерти\nVIP профессии\nИ МНОГОЕ ДРУГОЕ\n(Со временем возможности пополняются)' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'vip', 720 )
		ePly:ChatSend( '~AMBI~ • ~W~ Вы получили VIP на 30 дней' )
	end )
:End()

IGS( 'VIP', 'priv1_forever' )
	:SetPrice( 199 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/vip.png' )
	:SetDescription( '- 3-е лицо\n- Перма оружие\nКрасивый таб\nБольше места в инвентаре\nВдвое быстрее экран после смерти\nVIP профессии\nИ МНОГОЕ ДРУГОЕ\n(Со временем возможности пополняются)' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'vip', -1 )
		ePly:ChatSend( '~AMBI~ • ~W~ Вы получили VIP навсегда!' )
	end )
:End()

IGS( 'Premium [30 Дней]', 'priv2' )
	:SetPrice( 500 )
	:SetTerm( 30 )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/prem.png' )
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( 'Привилегия\nВсе крутые пушки в /kit weapons\nx3 Зарплата и опыт\nДоступны ВСЕ профессии\nДоступен самый лучший Маник\nДоступны все Способности\nДоступна возможность смены Playermodel\nДоступен /kit premium\nИ МНОГОЕ ДРУГОЕ(Со временем будет пополняться)' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'premium', 720 )
		ePly:ChatSend( '~AMBI_PURPLE~ • ~W~ Вы получили Premium на 30 дней' )
	end )
:End()

IGS( 'Premium', 'priv2_forever' )
	:SetPrice( 1500 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/prem.png' )
	:SetDescription( 'Привилегия\nВсе крутые пушки в /kit weapons\nx3 Зарплата и опыт\nДоступны ВСЕ профессии\nДоступен самый лучший Маник\nДоступны все Способности\nДоступна возможность смены Playermodel\nДоступен /kit premium\nИ МНОГОЕ ДРУГОЕ(Со временем будет пополняться)' )
	:SetOnActivate( function( ePly )
		ePly:SetPrivilege( 'premium', -1 )
		ePly:ChatSend( '~AMBI_PURPLE~ • ~W~ Вы получили Premium навсегда' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Ранги'

IGS( 'Support', 'rank1' )
	:SetPrice( 99 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность мута и размута\n• Брать физганом игроков' )
	:SetOnActivate( function( ePly )
		RunConsoleCommand( 'ulx', 'adduser', ePly:Name(), 'dsupport', '-1' )
		
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ Спасибо! Если не выдался ранг, обратитесь к админам' )
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ У вас есть 24 часа, чтобы в /discord подать заявку' )
		ePly:Notify( 'У вас есть 24 часа, чтобы в /discord подать заявку', 30 )
	end )
:End()

IGS( 'Д-Модератор', 'rank2' )
	:SetPrice( 800 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• ВОЗМОЖНОСТИ ПРЕДЫДУЩЕГО РАНГА\n• Джаил \n• Телепорты \n• Невидимость\n• Заморозка\n• Бессмертие\n• Убить игрока (!slay)\n• Следить за игроком\n• NoClip\n• Кик\n• Логи\n• Выдавать и отбирать лицензию\n• Сделать РП-имя игроку\n• Продать дверь игроку\n• Уволить игрока' )
	:SetOnActivate( function( ePly )
		RunConsoleCommand( 'ulx', 'adduser', ePly:Name(), 'dmoder', '-1' )
		
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ Спасибо! Если не выдался ранг, обратитесь к админам' )
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ У вас есть 24 часа, чтобы в /discord подать заявку' )
		ePly:Notify( 'У вас есть 24 часа, чтобы в /discord подать заявку', 30 )
	end )
:End()

IGS( 'Суперадмин', 'rank3' )
	:SetPrice( 1200 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• ВОЗМОЖНОСТИ ПРЕДЫДУЩЕГО РАНГА\n• Выдать броню\n• Превратить игрока в ragdoll\n• Отобрать оружие и игрока\n• Начать и остановить голосование\n• Выдать Warn\n• Очистисть и задать законы\n• Выдать или снять арест\n• Выдать или снять розыск\n• Видеть анонимные сообщения\n• Больше лимиты наказания, чем у прошлого ранга' )
	:SetOnActivate( function( ePly )
		RunConsoleCommand( 'ulx', 'adduser', ePly:Name(), 'dsadmin', '-1' )
		
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ Спасибо! Если не выдался ранг, обратитесь к админам' )
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ У вас есть 24 часа, чтобы в /discord подать заявку' )
		ePly:Notify( 'У вас есть 24 часа, чтобы в /discord подать заявку', 30 )
	end )
:End()

IGS( 'Куратор', 'rank4' )
	:SetPrice( 2500 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• ВОЗМОЖНОСТИ ПРЕДЫДУЩЕГО РАНГА\n• Снять Джаил\n• Выдать бан по id\n• Выдавать и снимать донатный варн\n• Спавн игрока\n• Больше лимиты наказания, чем у прошлого ранга' )
	:SetOnActivate( function( ePly )
		RunConsoleCommand( 'ulx', 'adduser', ePly:Name(), 'dcurator', '-1' )
		
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ Спасибо! Если не выдался ранг, обратитесь к админам' )
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ У вас есть 24 часа, чтобы в /discord подать заявку' )
		ePly:Notify( 'У вас есть 24 часа, чтобы в /discord подать заявку', 30 )
	end )
:End()

IGS( 'Старший Куратор', 'rank5' )
	:SetPrice( 5000 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• ВОЗМОЖНОСТИ ПРЕДЫДУЩЕГО РАНГА\n• Поджечь игрока\n• Выставить HP\n• Обычный бан и разбан\n• Смотреть админ варны\n• Больше лимиты наказания, чем у прошлого ранга' )
	:SetOnActivate( function( ePly )
		RunConsoleCommand( 'ulx', 'adduser', ePly:Name(), 'd-senior-curator', '-1' )
		
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ Спасибо! Если не выдался ранг, обратитесь к админам' )
		ePly:ChatSend( '~HOMEWAY_BLUE~ • ~W~ У вас есть 24 часа, чтобы в /discord подать заявку' )
		ePly:Notify( 'У вас есть 24 часа, чтобы в /discord подать заявку', 30 )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Возможности'

IGS( 'Говорилка', 'ability_tts' )
	:SetPrice( 199 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность даёт возможность юзать TTS\n/tts on - включить\n/tts off - выключить\n/tts voice - поменять голос (/tts voice zahar)\nНельзя постить большие сообщения или ссылки\nОстаётся навсегда' )
	:SetNetworked( true )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/voice.png' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за донат на Homeway' )
		ePly:ChatSend( '~W~ Включить ~B~ /tts on' )
		ePly:ChatSend( '~W~ Отключить ~R~ /tts on' )
		ePly:ChatSend( '~W~ Изменить Голос ~G~ /tts voice' )

		Ambi.Homeway.NotifyAll( ePly:Name()..' купил Говорилку [F6]', 30 )
	end )
:End()

IGS( 'Убрать Анти-БХОП', 'ability_disable_antibhop' )
	:SetPrice( 75 )
	:SetPerma()
	:SetStackable( false )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность спокойно БХопить, но нельзя слишком сильно разгоняться\nНельзя юзать разгон\nОстаётся навсегда' )
	:SetNetworked( true )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/bunny.png' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 💙 Спасибо за донат на Homeway' )

		Ambi.Homeway.NotifyAll( ePly:Name()..' купил АнтиБХОП [F6]', 30 )
	end )
:End()

IGS( 'Глобал Сообщение', 'ability_global_msg' )
	:SetPrice( 30 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetIcon( 'https://ltdfoto.ru/images/2024/08/22/alert.png' )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность выводит на экран сообщение' )
	:SetOnActivate( function( ePly )
		ePly:ChatSend( '~W~ 😭 Пока не работает. Обратись к Титановскому, шобы пофиксил' )
	end )
:End()

IGS( '+100 HP всем', 'ability_hp100' )
	:SetPrice( 50 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность даёт 100 хп всем игрокам!' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/medical-3d-render-icon-illustration-png.png' )
	:SetOnActivate( function( ePly )
		for _, ply in ipairs( player.GetAll() ) do
			if not ply:Alive() then return end

			ply:SetHealth( ply:Health() + 100 )
			ply:Notify( 'Игрок '..ePly:Name()..' купил всем +100 ХП', 10 )
		end
	end )
:End()

IGS( '+100 Armor всем', 'ability_armor100' )
	:SetPrice( 50 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( '• Возможность даёт 100 брони всем игрокам!' )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/6174546-1.png' )
	:SetOnActivate( function( ePly )
		for _, ply in ipairs( player.GetAll() ) do
			if not ply:Alive() then return end

			ply:SetArmor( ply:Armor() + 100 )
			ply:Notify( 'Игрок '..ePly:Name()..' купил всем +100 Armor', 10 )
		end
	end )
:End()

IGS( 'Зафулить Склад Полиции', 'ability_fill_w_police' )
	:SetPrice( 30 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/warehouse.png' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/15/gmod_hQThfYIC0V.jpg' )
	:SetDescription( '• Возможность добавляет максимум оружия у склада Полиции\nЕсли максимума нет - то 100 единиц\nТакже добавляет 3000 патронов' )
	:SetOnActivate( function( ePly )
		for _, warehouse in ipairs( ents.FindByClass( 'warehouse' ) ) do
			if ( warehouse:GetWarehouse() ~= 'police' ) then continue end

			local wh = Ambi.Homeway.GetWarehouse( warehouse:GetWarehouse() )

			for i, wep in ipairs( wh.items ) do
                local count = wep.max or 100

                warehouse:SetWeaponCount( i, count )
            end
			
			warehouse:SetAmmo( warehouse:GetAmmo() + 3000 )
		end

		Ambi.Homeway.NotifyAll( ePly:Name()..' зафулил склад Полиции', 15 )
	end )
:End()

IGS( 'Зафулить Склад ФБР', 'ability_fill_w_fbi' )
	:SetPrice( 30 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/warehouse.png' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/15/gmod_ot1vBOjU7U.jpg' )
	:SetDescription( '• Возможность добавляет максимум оружия у склада ФБР\nЕсли максимума нет - то 100 единиц\nТакже добавляет 3000 патронов' )
	:SetOnActivate( function( ePly )
		for _, warehouse in ipairs( ents.FindByClass( 'warehouse' ) ) do
			if ( warehouse:GetWarehouse() ~= 'fbi' ) then continue end

			local wh = Ambi.Homeway.GetWarehouse( warehouse:GetWarehouse() )

			for i, wep in ipairs( wh.items ) do
                local count = wep.max or 100

                warehouse:SetWeaponCount( i, count )
            end
			
			warehouse:SetAmmo( warehouse:GetAmmo() + 3000 )
		end

		Ambi.Homeway.NotifyAll( ePly:Name()..' зафулил склад FBI', 15 )
	end )
:End()

IGS( 'Зафулить Склад Мафии', 'ability_fill_w_mafia' )
	:SetPrice( 299 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetIcon( 'https://ltdfoto.ru/images/2024/09/15/warehouse.png' )
	:SetImage( 'https://ltdfoto.ru/images/2024/09/15/gmod_OjCXbqXxZi.jpg' )
	:SetDescription( '• Возможность добавляет максимум оружия у склада Мафии\nЕсли максимума нет - то 100 единиц\nТакже добавляет 3000 патронов' )
	:SetOnActivate( function( ePly )
		for _, warehouse in ipairs( ents.FindByClass( 'warehouse' ) ) do
			if ( warehouse:GetWarehouse() ~= 'mafia' ) then continue end

			local wh = Ambi.Homeway.GetWarehouse( warehouse:GetWarehouse() )

			for i, wep in ipairs( wh.items ) do
                local count = wep.max or 100

                warehouse:SetWeaponCount( i, count )
            end
			
			warehouse:SetAmmo( warehouse:GetAmmo() + 3000 )
		end

		Ambi.Homeway.NotifyAll( ePly:Name()..' зафулил склад Мафии', 15 )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Питомцы'

-- todo battlepass
-- IGS( 'НЛО', 'pet_ufo' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Макарошка', 'pet_makaroshka' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Головач Лена', 'pet_head' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Квантовая Сфера', 'pet_quant_sphere' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Бургер', 'pet_burger' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Кукла', 'pet_burger' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Череп', 'pet_burger' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Арбуз Бейби', 'pet_burger' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- IGS( 'Конь', 'pet_burger' )
-- 	:SetPrice( 199 )
-- 	:SetTerm( 0 )
-- 	:SetStackable( true )
-- 	:SetCategory( CATEGORY )
-- 	:SetIcon( 'https://www.freepnglogos.com/uploads/ufo-png/ufo-ufovisitors-ufos-1.png' )
-- 	:SetDescription( 'В инвентарь даётся предмет, не забудьте подготовить всё!\n Питомец следует за хозяином и может давать некоторые баффы' )
-- 	:SetOnActivate( function( ePly )
-- 		ePly:AddInvItemOrDrop( 'pet_ufo', 1 )
-- 	end )
-- :End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Индивидуальные'

IGS( 'Звук при спавне', 'make_sound_spawn' )
	:SetPrice( 650 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Ваш звук при спавне (не более 5-ти секунд).\nЧтобы приобрести и обсудить детали - обратитесь в /discord.' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Спасибо!' )
	end )
:End()

IGS( 'Питомец', 'make_pet' )
	:SetPrice( 900 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Индивидуальный питомец.\nЧтобы приобрести и обсудить детали - обратитесь в /discord.' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Работа', 'make_job' )
	:SetPrice( 3000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Индивидуальная профессия.\nЧтобы приобрести и обсудить детали - обратитесь в /discord.' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'PlayerModel', 'make_model' )
	:SetPrice( 2000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Индивидуальный скин.\nЧтобы приобрести и обсудить детали - обратитесь в /discord.' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Оружие', 'make_swep' )
	:SetPrice( 3000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Индивидуальный SWAP.\nЧтобы приобрести и обсудить детали - обратитесь в /discord.' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

-- ------------------------------------------------------------------------------------------------------
local CATEGORY = 'Приваты'

IGS( 'Территория', 'private_terra' )
	:SetPrice( 1500 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Покупка территории на карте\nКаждый месяц аренда - 500 рублей' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Здание из карты', 'private_building' )
	:SetPrice( 3000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Покупка территории на карте\nКаждый месяц аренда - 500 рублей' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()

IGS( 'Здание по Чертежам', 'private_self_building' )
	:SetPrice( 7000 )
	:SetTerm( 0 )
	:SetStackable( true )
	:SetCategory( CATEGORY )
	:SetDescription( 'Покупка территории на карте\nКаждый месяц аренда - 500 рублей' )
	:SetOnActivate( function( ePly )
		ePly:ChatPrint( 'Обратитесь к Администрации' )
	end )
:End()